server:
  port: 8085

spring:
  application:
    name: email-service

# Azure Communication Service (disabled by default)
azure:
  communication:
    enabled: false
    connection-string: ${AZURE_COMMUNICATION_CONNECTION_STRING:}

# Logging
logging:
  level:
    com.credexa.email: DEBUG
    com.azure: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
